
import os
import re

BLOGS_DIR = "content/blogs"

def clean_text(text):
    # Remove bolding
    text = text.replace("**", "")
    
    # Fix em-dashes
    text = text.replace("—", " - ")
    
    # Remove emojis (Supplementary plane + common ranges)
    text = re.sub(r'[\U00010000-\U0010ffff]', '', text)
    text = re.sub(r'[\u2700-\u27BF]', '', text) 
    text = re.sub(r'[\u2600-\u26FF]', '', text)
    
    # Fix multiple spaces generated by removal
    text = re.sub(r' +', ' ', text)
    
    return text

def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            frontmatter = parts[1]
            body = parts[2]
            
            # Clean body
            body = clean_text(body)
            
            # Remove the first H1/H2 if it duplicates the title (common in these imports)
            # Simple heuristic: remove first non-empty line if it starts with #
            lines = body.split('\n')
            cleaned_lines = []
            title_removed = False
            for line in lines:
                sline = line.strip()
                if not sline:
                    cleaned_lines.append(line)
                    continue
                if not title_removed and sline.startswith('#'):
                    title_removed = True
                    continue # Skip the title header
                cleaned_lines.append(line)
            
            body = '\n'.join(cleaned_lines)
            
            new_content = f"---{frontmatter}---{body}"
            
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(new_content)
            print(f"Processed {filepath}")

def main():
    if not os.path.exists(BLOGS_DIR):
        print(f"Directory {BLOGS_DIR} not found.")
        return

    for filename in sorted(os.listdir(BLOGS_DIR)):
        if filename.endswith(".md"):
            process_file(os.path.join(BLOGS_DIR, filename))

if __name__ == "__main__":
    main()
